### ISSUE TITLE
Provide an appimage

### ISSUE THREAD

**Issue by eugenialoli** [trelby/trelby#48]
Please provide an appimage, building using virtual environments of python under debian was not easy (the system wouldn't let me use directly pip3 to install it), and it ultimately failed. An appimage would deal with that better.

**Comment by limburgher** [comment]
Thank you, I'll look into that. We already have a Flatpak available if that helps. I'd meant to checking into app images but (gestures at everything).

I can also assist with pip installation; I was actually providing .deb files until the last release. I need to update those but it was a major packaging/code structure change.

**Comment by voprop** [comment]
Hi!
I'm assuming you're using debian 12. Debian administrators and package managers decided to not allow by default directly using pip. Not sure they're reasoning, but fear not, there is an easy way around it. Ensure you have the venv package that lets you create a virtual environment.

Say you do:
`python3 -m venv $HOME/TrelbyPip` and then type on the command line:
`source $HOME/TrelbyPip/bin/activate`

Once in the virtual environment, now you can type `pip3 install trelby`. Trelby will be installed to the same directory you installed the virtual environment in.

**Comment by Samueru-sama** [comment]
The following script will produce the AppImage and it should work on any linux system given that I'm bundling all the dependencies: 

```
#!/usr/bin/env bash
# archlinux deps: python musl base-devel libglvnd wget zsync

set -eu

PACKAGE="trelby"
export APPIMAGE_EXTRACT_AND_RUN=1
export ARCH="$(uname -m)"
UPINFO="gh-releases-zsync|$(echo $GITHUB_REPOSITORY | tr '/' '|')|latest|*$ARCH.AppImage.zsync"
APPIMAGETOOL="https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
ICON="https://github.com/trelby/trelby/blob/master/trelby/resources/icon256.png?raw=true"
DESKTOP="https://raw.githubusercontent.com/trelby/trelby/refs/heads/master/trelby/resources/trelby.desktop"

# PREPARE APPDIR
mkdir -p ./"$PACKAGE"/build-env
cd "$PACKAGE"
python -m venv build-env
. build-env/bin/activate
python -m pip install --no-cache-dir --upgrade --force --ignore-installed pip
python -m pip install --no-cache-dir --upgrade wheel pyinstaller
python -m pip install --no-cache-dir --upgrade trelby

VERSION="$(python -m pip show trelby 2>/dev/null | awk '/Version:/ {print $2; exit}')"

cp /usr/lib/ld-musl-x86_64.so.1 libc.musl-x86_64.so.1
pyinstaller --name trelby --target-arch x86_64 --strip --noupx \
	--add-data build-env/lib/python*/site-packages/trelby:trelby \
	--add-data /usr/lib/libresolv.so.2:. \
	--add-data /usr/lib/librt.so.1:. \
	--add-data /usr/lib/libm.so.6:. \
	--add-data /usr/lib/libxcb.so.1:. \
	--add-data /usr/lib/libGLX.so.0:. \
	--add-data /usr/lib/libGLdispatch.so.0:. \
	--add-data /usr/lib/libGL.so.1:. \
	--add-data libc.musl-x86_64.so.1:. \
	"$(command -v trelby)"

mv ./dist/trelby ./AppDir
mkdir -p ./AppDir/lib
ldd ./AppDir/trelby | awk -F"[> ]" '{print $4}' | xargs -I {} cp -f {} ./AppDir/lib
mv ./AppDir/lib/ld-linux-x86-64.so.2 ./AppDir
patchelf --set-rpath '$ORIGIN' ./AppDir/lib/*
patchelf --set-rpath '$ORIGIN/lib' ./AppDir/trelby

echo '#!/usr/bin/env sh
HERE="$(dirname "$(readlink -f "$0")")"
exec "$HERE/ld-linux-x86-64.so.2" "$HERE/trelby" "$@"' > ./AppDir/AppRun
chmod +x ./AppDir/AppRun

wget "$ICON" -O ./AppDir/trelby256.png
ln -s ./trelby256.png ./AppDir/.DirIcon
wget "$DESKTOP" -O ./AppDir/trelby.desktop

# MAKE APPIMAGE
wget -q "$APPIMAGETOOL" -O ./appimagetool
chmod +x ./appimagetool
./appimagetool -n -u "$UPINFO" \
	--comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 22 \
	"$PWD"/AppDir "$PWD"/"$PACKAGE"-"$VERSION"-anylinux-"$ARCH".AppImage
mv ./*.AppImage* ../
cd ..
echo "All done!"
```

[link](https://mega.nz/file/QVhgTA6S#QUUZyoQKgZ6alrUxPcxwL3lKmzVvrVT_nT7609uzd2c)

I made the AppImage on Artixlinux and tested it on ubuntu20.04 and voidlinux **musl** and it seems to work fine, some tweaking might be needed since I just took the existing script from another python appimage that I have and modified it to be used here, so maybe there are some dependencies being deployed that are not really needed at all. 

![image](https://github.com/user-attachments/assets/452388a1-04f3-4181-b81a-3df2ab4fc6ee)

![image](https://github.com/user-attachments/assets/9a0e0708-ce10-4915-b411-2ccd63de79d7)

**Comment by voprop** [comment]
@Samueru-sama 
How would you convert that to a github actions so @limburgher can run it automatically?

**Comment by limburgher** [comment]
Also, I don't have gh-releases-zsync. Not sure where that comes from.

**Comment by Samueru-sama** [comment]
> @Samueru-sama How would you convert that to a github actions so @limburgher can run it automatically?

It already can, just spin an archlinux/artixlinux container to make the appimage, the script is all ready in that case.

[For example](https://github.com/pkgforge-dev/puddletag-AppImage/blob/main/.github/workflows/blank.yml#L11-L30)

Or if you like to build on ubuntu then use that, but in that case some modifications might be needed since you can see that I add/copy some libraries from `/usr/lib` and on ubuntu the path is going to be different, something like `/usr/lib/x86_64-linux-gnu` iirc. 

Then it is up to the owner to choose what do to with the produced appimage, some people make nightly releases that get produced on each commit for testing or similar, others setup the CI to instead be manually triggered for releases, etc, etc. 

>Also, I don't have gh-releases-zsync. Not sure where that comes from.

`gh-releases-zsync` is part of `UPINFO="gh-releases-zsync|$(echo $GITHUB_REPOSITORY | tr '/' '|')|latest|*$ARCH.AppImage.zsync"`

`UPINFO` is the update information that gets embedded in the AppImage runtime for updates with [AppImageUpdate](https://github.com/AppImageCommunity/AppImageUpdate), it is a variable that gets passed to `appimagetool` later down in the script. As long as you are going to run that in github actions nothing needs to change, and nothing breaks either if the script is ran locally on your PC, just that you can't update the appimage. the part that says `$(echo $GITHUB_REPOSITORY | tr '/' '|')` will be resolved in this case to `trelby|trelby`, which with the rest of the information it tells AppImageUpdate where to look for the zsync file for updating.

**Comment by limburgher** [comment]
I mean what package installs gh-releases-zsync?

**Comment by Samueru-sama** [comment]
> I mean what package installs gh-releases-zsync?

Nothing, it is information for AppImageUpdate that gets embedded in the AppImage. 

Using the same puddletag example:

![image](https://github.com/user-attachments/assets/392d2f26-02aa-492c-aef7-83548e4ecb72)

`Raw update information: gh-releases-zsync|pkgforge-dev|puddletag-AppImage|latest|*x86_64.AppImage.zsync`

This information tells appimageupdate where to look for the `Assembled ZSync URL`, which it correctly found as `https://github.com/pkgforge-dev/puddletag-AppImage/releases/download/2.4.0/puddletag-2.4.0-anylinux-x86_64.AppImage.zsync` in this example.

**Comment by eugenialoli** [comment]
I can confirm that the Trelby appimage is working on Linux Mint 22. Thank you for that.
Originally I tried to install it as mentioned in the docs, and it was taking forever on this Macbook Air 2015, particularly compiling the wxpy bindings. My macbook was getting so hot, that I had to stop the installation.  I'm so happy for this appimage, I hope you start offering Trelby as both Appimage, and Flatpaks, because it's a great app, and people should know it more.

**Comment by limburgher** [comment]
Gotcha.

@eugenialoli BTW I've fixed the deb builds at: https://build.opensuse.org/package/show/home:gwync/trelby

**Comment by voprop** [comment]
@eugenialoli 
It's already on flathub.
https://flathub.org/apps/org.trelby.Trelby

**Comment by rcentros** [comment]
I'm trying to get this script to work on Linux Mint and, I've gotten to the point where it compiles Trelby (it took a while but I'm slow), but now it's stopping here...

`mv: cannot overwrite non-directory './AppDir/trelby' with directory './dist/trelby'`

I've created AppDir in my home folder and a trelby sub-directory, so I'm having troubling figuring out what "non-directory" means in this error message.

Also curious to know that, if I do somehow get this to work, will it automatically download the newest release of Trelby? 

Thanks for any information. The AppImage file that's pre-made has worked in a Chromebook (running Debian 10) and two versions of Linux Mint (22 and 21.3).

**Comment by Samueru-sama** [comment]
> I'm trying to get this script to work on Linux Mint and, I've gotten to the point where it compiles Trelby (it took a while but I'm slow), but now it's stopping here...
> 
> `mv: cannot overwrite non-directory './AppDir/trelby' with directory './dist/trelby'`
> 
> I've created AppDir in my home folder and a trelby sub-directory within it, so I'm having troubling figuring out what "non-directory" means in this error message.
> 
> Also curious to know that, if I do somehow get this to work, will it automatically download the newest releases of Trelby?
> 
> Thanks for any information. The AppImage file that's pre-made has worked in a Chromebook (running Debian 10) and two versions of Linux Mint (22 and 21.3).

The `mv` would be coming from line 38: `mv ./dist/trelby ./AppDir` which is just moving and renaming the resulting pyinstaller `./dist/trelby` to `./AppDir`

I don't know how you got that error, but somehow you already have `./AppDir` before that command is ran and it so just happens that `./AppDir/trelby` also exists, which is the trelby binary in the AppDir. 

>I've created AppDir in my home folder and a trelby sub-directory within it, so I'm having troubling figuring out what "non-directory" means in this error message.

You don't have to make the AppDir, you just need to run the script anywhere where your user has write access and it will automatically make a `./trelby`directory and do the rest inside of that dir.

Note that on debian based systems there are no such things as `/usr/lib/libresolv.so.2` `/usr/lib/librt.so.1`, etc, etc libraries are usually inside another directory in `/usr/lib` called `x86_64-linux-gnu` and the script would need to be modified to take that into account. 

Also I just noticed that on the list of dependencies I forgot to include `patchelf`, just added it.

>Also curious to know that, if I do somehow get this to work, will it automatically download the newest releases of Trelby?

For this to happen the appimage would need to start being released on a repository and you would need to have an appimage manager that makes use of appimageupdate, like AM or the go-appimage daemon.  Gearlever is similar but iirc it doesn't make use of appimageupdate and instead asks you to give the url to check for updates. 

Other developers add the self update functionality in the application itself, the appimage runtime sets the env variable `$APPIMAGE` which contains the fullpath to the appimage with symlinks resolved and they would just need to download a new version and replace the existing appimage but that's a lot more of work.

**Comment by rcentros** [comment]
I forgot to mention that line 9 (I believe the zsync line) returns an "unbound variable" error. I probably should have mentioned that first.

**Comment by Samueru-sama** [comment]
> I forgot to mention that line 9 (I believe the zsync line) returns an "unbound variable" error. I probably should have mentioned that first.

Not an issue, that's because the script isn't being ran on github actions. `$GITHUB_REPOSITORY` is a variable that github sets, which in the case of this repo would be `trelby/trelby`. 

However AppImageUpdate wants the update information separated by `|` instead of `/`, so to fix that issue it just runs `$(echo $GITHUB_REPOSITORY | tr '/' '|')` which will make it look as `trelby|trelby`. That entire `$UPINFO` var ends up being embedded in the produced AppImage (you can actually do this manually with `objcopy` as well) and it is just meant to be read by AppimageUpdate. 

Since the script has `set -u` for good practice™ this causes the subshell to error out because `$GITHUB_REPOSITORY` is not set, that's all the error means, the rest of the script will continue as normal.

**Comment by rcentros** [comment]
I installed Artix in VirtualBox and ran the AppImage script. It took forever to make the wxPython "wheel," but that's normal for me when doing a Python install of Trelby. Once that was done, though, it created the AppImage file with the message that it was a success. But when I try running the AppImage I get these errors... (maybe I started the script in the wrong directory?).

```
$ ./trelby-2.4.12-anylinux-x86_64.AppImage 
Traceback (most recent call last):
  File "trelby/trelby.py", line 134, in makeConfDir
    os.mkdir(misc.toPath(misc.confPath), mode=0o755)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: b'/home/rcentros.config/trelby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trelby/trelby.py", line 2700, in OnInit
    gd = GlobalData()
  File "trelby/trelby.py", line 127, in __init__
    self.makeConfDir()
    ~~~~~~~~~~~~~~~~^^
  File "trelby/trelby.py", line 135, in makeConfDir
    except OSError(os.errno, os.strerror):
                   ^^^^^^^^
AttributeError: module 'os' has no attribute 'errno'. Did you mean: 'error'?
OnInit returned false, exiting...
```
I'm wondering if an AppImage could be made from a Git install — for some reason there's no three or four hour wxPython wheel creation wit the Git install.

At any rate, if anyone can point out where I screwed up, I would appreciate it.

Thanks everyone for all the work. I'm still amazed at all that happened in a couple days. I would love to get the Git version of Trelby 2.4.12 into an AppImage and post it at the AppImage Hub.

**Comment by voprop** [comment]
@rcentros 
Was your username literally "rcentos.config"? Because the first part after home is your username if you don't know.
`/home/foo/bar/foobar` would have foo as the username and the rest is part of the $HOME directory. Now, I while it's technically valid and allowed to have a period in the name, it's strongly discouraged because it can screw up scripts and it cannot for some reason find the path to make the subdirectory.

**Comment by rcentros** [comment]
I don't think this is an AppImage issue. I'm getting the same error while trying a git install on Live USB version of Linux Mint 22...
```
mint@mint:~/trelby$ python3 trelby.py
Traceback (most recent call last):
  File "/home/mint/trelby/trelby/trelby.py", line 137, in makeConfDir
    os.mkdir(misc.toPath(misc.confPath), mode=0o755)
FileNotFoundError: [Errno 2] No such file or directory: b'/home/mint.config/trelby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mint/trelby/trelby/trelby.py", line 2715, in OnInit
    gd = GlobalData()
         ^^^^^^^^^^^^
  File "/home/mint/trelby/trelby/trelby.py", line 130, in __init__
    self.makeConfDir()
  File "/home/mint/trelby/trelby/trelby.py", line 138, in makeConfDir
    except OSError(os.errno, os.strerror):
                   ^^^^^^^^
AttributeError: module 'os' has no attribute 'errno'. Did you mean: 'error'?
OnInit returned false, exiting...
```

I'm also getting an error with the .deb version of 2.4.13...

```
mint@mint:~/trelby$ trelby
Traceback (most recent call last):
  File "/usr/bin/trelby", line 5, in <module>
    from trelby import trelby
ModuleNotFoundError: No module named 'trelby'
```
It looks something may not be quite right in the directory locations (or pointers to those locations.)

**Comment by limburgher** [comment]
I just pushed a fix for the path issue to master, please try again.

**Comment by rcentros** [comment]
I am trying now, but I stupidly deleted the whole Trelby folder instead of just the AppDir folder, so now I have to rebuild the wxPython wheel again — which takes about three or four hours on the Artix virtual machine on that computer. 

Not my finest moment. Sorry for the delay.

**Comment by limburgher** [comment]
No worries, you're hardly the first. ;)

**Comment by Samueru-sama** [comment]
I built the AppImage again a few hours ago before the fix and yeah there was a big oopsie in the way the config dir was made: 

![image](https://github.com/user-attachments/assets/e0101366-e67d-42d1-89a7-d286668a226a)

The app still ran though, maybe it is because I have `XDG_CONFIG_HOME` otherwise trelby would have tried to make a `/home/${USER}trelby` dir (notice the lack of slash) which lacks permissions to do so.

**Comment by rcentros** [comment]
> No worries, you're hardly the first. ;)

Git works again. Thanks.

**Comment by rcentros** [comment]
I re-ran Samueru-sama's AppImage script again. It produced a working AppImage... mostly. I tested it successfully on Linux 22.1, Fedora 41, Manjaro 24.05.240xxx. Everything worked on these, Fedora did not show the icon, but otherwise worked. I then tried it on Ubuntu 22.04 and Debian 12... and the problem with not being able to use the PDF application cropped up on these two. Same issue I have with the Flatpak version on Linux Mint(?). At any rate, if someone wants to test the AppImage, I've posted it on my Google Drive. Maybe the fact that I was testing on live USB "installs" has something to do with the PDF not working. (I hope.) 

If the AppImage works, it would be nice to put it up on AppImage Hub. Here it is...

https://drive.google.com/file/d/1gvpaFCapwCfnvTBZrX6EmEiWtc-uEOz5/view?usp=sharing

**Comment by Samueru-sama** [comment]
@limburgher do you need help setting up the appimage CI or are you nah on it? If it is the later I can set up a set a repo to generate the appimage and give it to @rcentros lol

**Comment by rcentros** [comment]
> [@limburgher](https://github.com/limburgher) do you need help setting up the appimage CI or are you nah on it? If it is the later I can set up a set a repo to generate the appimage and give it to [@rcentros](https://github.com/rcentros) lol

I don't know anything about this. Just followed your advice and "installed" Artix in a virtual machine and ran the script you provided. 

The thing about AppImages is that, once you have a stable version (like 2.4.14) you don't have to update it constantly. (Unless there are new features someone really wants.) The way I see 2.4.14 is that this is the first version where everything really works well. (And it even has the new feature of hiding the toolbar.) 

I've found that, in all Debian-based distributions I've tested, all the dependencies are met by running these five commands in a shell script...

```
sudo apt install python3-wxgtk4.0
sudo apt install python3-lxml
sudo apt install python3-reportlab
sudo apt install git
git clone https://github.com/trelby/trelby.git
```

You don't even have to run make, all you have to do is make shell script to run trelby.py and create a launcher for it.

I've written a longer shell script that automatically downloads Courier Prime, and Courier Screenplay, installs them in the .fonts directory and asks for the user name so they're set up as the PDF files. I also automatically install configuration files and my themes (included in another zip file). I can also change the default paper form A4 to Letter with the Letter version of the script.

```
cd ~/trelby/trelby
sed -i 's/297.0/279.4/' config.py
sed -i 's/210.0/215.9/' config.py
```
So I've got two versions of the installer (one for A4 without these last three lines). I'm sure the shell script is clumsily written, but it works.

I'll see if I can run your AppImage script again with the Paper changed to Letter as the default.

**Comment by Samueru-sama** [comment]
https://github.com/pkgforge-dev/Trelby-AppImage
