### ISSUE TITLE
An error ?

### ISSUE THREAD

**Issue by Ascol57** [trelby/trelby#7]
Hello.
I would like install Trebly but when I execute it : 

Traceback (most recent call last):
  File "trelby.py", line 2697, in <module>
  File "trelby.py", line 2694, in main
  File "wx\_core.pyo", line 7981, in __init__
  File "wx\_core.pyo", line 7555, in _BootstrapApp
  File "trelby.py", line 2608, in OnInit
  File "misc.pyo", line 60, in init
  File "encodings\utf_8.pyo", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 11: invalid continuation byte

In the .log file

Why ?

**Comment by xucaen** [comment]
I had no problems installing Trelby v2.2 on windows 10. You might need to update windows, looks like your installation doesn't support UTF8.

**Comment by limburgher** [comment]
Try the PyPi version: pip install trelby.
