### ISSUE TITLE
Trelby cannot be opened

### ISSUE THREAD

**Issue by clementin-bonneau-riera** [trelby/trelby#9]
I can't open Trelby on Windows 10. The same problem occurs every time I open and install.
It seems to be [due to an e in my username.](https://groups.google.com/g/trelby/c/0TJjpMylktI?pli=1).

I guess a fix won't be released but if anyone knows how to work around this problem.

Thank you

- last release used
- regular installation
- no issue on linux version (Fedora 36)

![image](https://user-images.githubusercontent.com/79161093/191062202-cc3b7733-588f-47b8-8cbf-5fd8e6a4a4fa.png)

trelby.exe.log

```Txt
Traceback (most recent call last):
  File "trelby.py", line 2697, in <module>
  File "trelby.py", line 2694, in main
  File "wx\_core.pyo", line 7981, in __init__
  File "wx\_core.pyo", line 7555, in _BootstrapApp
  File "trelby.py", line 2608, in OnInit
  File "misc.pyo", line 60, in init
  File "encodings\utf_8.pyo", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 11: invalid continuation byte
```

**Comment by anilgulecha** [comment]
Trelby isn't maintained anymore. For anyone looking for an alternative FOSS screenwriter, I can highly recommend scrite.io 

Cheers

**Comment by Freple** [comment]
![image](https://github.com/user-attachments/assets/e80b4e29-defe-4e1b-bfed-1fb42f394091)
:(

**Comment by UnisTorvalds** [comment]
Has the new version fixed this? Can this issue be closed?

**Comment by UnisTorvalds** [comment]
Sorry I was asking OP.  I don't have Windows so can't test it.  But if it works through pip maybe we can close this ticket?

Discussion: I wonder whether the real issue is www.trelby.org ?  If people are coming to the app through the official website, the binaries on the download page are very out of date.  Maybe the binary downloads could be replaced with a link to GitHub?

**Comment by limburgher** [comment]
@anilgulecha I see the repo for trelby.githubio; how does that get deployed? I can update if needed.

**Comment by anilgulecha** [comment]
@limburgher It's via https://github.com/trelby/trelby.github.io . You just update the master branch, and changes will be auto deployed (it's GitHub pages)

**Comment by limburgher** [comment]
Try the PyPi version: pip install trelby.

**Comment by rcentros** [comment]
> Sorry I was asking OP. I don't have Windows so can't test it. But if it works through pip maybe we can close this ticket?
> 
> Discussion: I wonder whether the real issue is [www.trelby.org](http://www.trelby.org) ? If people are coming to the app through the official website, the binaries on the download page are very out of date. Maybe the binary downloads could be replaced with a link to GitHub?

I just installed Trelby 2.2 downloaded from the the trelby.org site. I think I've gotten the Python version to work on Windows 10, but I'm not positive about that. My user name also has an "e" so I'm not sure how that would apply. I'm also wondering why Scrite was mentioned?

**Comment by Bai-Long** [comment]
I just installed trelby on my Mac using the pip install trelby command. After searching the internet I figured out how to get a command that might launch the tool. (Nice try, but you don't deter me that easily!) 
But I get a "zsh: permission denied: trelby" error. I did not install it superuser or anything. Any ideas why this is?
